### ISSUE TITLE
Configuration 

### ISSUE THREAD

**Issue by hmert** [tmrts/Solomon#8]
Don't We need to make a config file? 

And schema.py is an install script?

**Comment by tmrts** [comment]
Absolutely!. Those are on my TO-DO list. I'll continue the project in April after my exams. Currently I'm using Graphite for the interface. I also plan to develop a lightweight dashboard alongside configuration and installation.

**Comment by hmert** [comment]
Please, share the TO-DO list or roadmap with the community.

**Comment by tmrts** [comment]
Done now. Thanks.
